
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ppp_loan_analysis'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ppp_loan_analysis'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example_models, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_pipeline:
    bronze:
      +materialized: table
      +schema: bronze
      +docs:
        node_color: "#CD7F32"

    silver:
      +materialized: view
      +schema: silver
      +docs:
        node_color: "#C0C0C0"

    gold:
      +materialized: view
      +schema: gold
      +docs:
        node_color: "#FFD700"
